language: node_js
os: osx
node_js:
  - "node"
cache:
  - yarn: true
before_install:
  - brew install gitversion
  - yarn global add json
install:
  - yarn install --frozen-lockfile

notifications:
  email: false

stages:
  - test
  - build
  - name: tag
    if: TRAVIS_PULL_REQUEST = false
  - name: release
    if: TRAVIS_PULL_REQUEST = false

jobs:
  include:
    - stage: test
      script: yarn test

    - stage: build
      script:
        - gitversion /output json | json MajorMinorPatch | xargs yarn run build --versionOverride

    - stage: tag
      script:
        - gitversion /output json | json MajorMinorPatch | xargs npm version
        - .travis/push.sh

    - stage: release
      script: echo "Pushing release to GitHub"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: dist/chrome.zip
        skip_cleanup: true
        on:
          tags: true
          branch: master