language: node_js
os: osx
node_js:
  - "node"
cache:
  - yarn: true
branches:
  only:
  - master
before_install:
  - brew install gitversion
  - yarn global add json
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build


notifications:
  email: false

stages:
  - build
  - test
  - name: tag
    if: branch = master AND TRAVIS_PULL_REQUEST = false
  - name: release
    if: branch = master AND TRAVIS_PULL_REQUEST = false

jobs:
  include:
    - stage: test
      script: yarn test

    - stage: build
      script:
        - gitversion | json MajorMinorPatch | xargs npm --no-git-tag-version --allow-same-version version
        - yarn run build

    - stage: tag
      script:
        - gitversion | json MajorMinorPatch | xargs npm --no-git-tag-version --allow-same-version version
        - .travis/commit.sh

    - stage: release
      script: echo "Pushing release to GitHub"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: output/chrome.zip
        skip_cleanup: true
        on:
          tags: true

          #TRAVIS_PULL_REQUEST