language: node_js
os: osx
git:
  depth: false
node_js:
  - "node"
cache:
  - yarn: true
before_install:
  - brew install gitversion
  - yarn global add json
  - git fetch --tags
install:
  - yarn install --frozen-lockfile

notifications:
  email: false

script:
  - ./.travis/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: dist/chrome.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master